[package]
name = "restaff-acp"
version = "0.1.0"
authors = ["Khoa Nguyen <'khoanta.96@gmail.com'>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["default", "blocking"] }
base64 = "0.13"
structopt = "0.3"
rpassword = "5"
serde_json = "1"
anyhow = "1"
